name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Install dependencies
      run: |
        npm install

    - name: Add Android platform
      run: |
        cordova platform add android

    - name: Build Android APK
      run: |
        cordova build android

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: dab-timer-apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
