name: Android CI

on:
  push:
    branches:
      - main
      - ui-enhancements
  pull_request:
    branches:
      - main
      - ui-enhancements
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Debug - Print current directory and list contents
      run: |
        pwd
        ls -R

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: DabTimer/android

    - name: Clean build
      run: ./gradlew clean
      working-directory: DabTimer/android

    - name: Build debug APK
      run: ./gradlew assembleDebug
      working-directory: DabTimer/android

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: DabTimer/android/app/build/outputs/apk/debug/app-debug.apk

