name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses || true
    
    - name: Install Android SDK components
      run: |
        sdkmanager "build-tools;34.0.0"
        sdkmanager "platforms;android-35"
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
    
    - name: Sync Capacitor
      run: npx cap sync android
    
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    
    - name: Decode Keystore
      if: ${{ secrets.RELEASE_KEY != '' }}
      run: |
        echo "${{ secrets.RELEASE_KEY }}" | base64 --decode > android/app/release-key.keystore
    
    - name: Build Android Release APK (Signed)
      if: ${{ secrets.RELEASE_KEY != '' }}
      run: |
        cd android
        ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=app/release-key.keystore \
          -Pandroid.injected.signing.store.password="${{ secrets.KEYSTORE_PASSWORD }}" \
          -Pandroid.injected.signing.key.alias="${{ secrets.KEY_ALIAS }}" \
          -Pandroid.injected.signing.key.password="${{ secrets.KEY_PASSWORD }}"
    
    - name: Build Android Debug APK (Unsigned)
      if: ${{ secrets.RELEASE_KEY == '' }}
      run: |
        cd android
        ./gradlew assembleDebug
    
    - name: Upload Release APK
      if: ${{ secrets.RELEASE_KEY != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release.apk
    
    - name: Upload Debug APK
      if: ${{ secrets.RELEASE_KEY == '' }}
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk

