name: Build Android APK (Release Signed)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-build-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > ${{ github.workspace }}/android/app/release-key.keystore

    - name: Build with Gradle (Release, Signed)
      run: ./gradlew assembleRelease
      env:
        KEYSTORE_PATH: ${{ github.workspace }}/android/app/release-key.keystore
        KEYSTORE_PASSWORD: android_store_pass
        KEY_ALIAS: release_key
        KEY_PASSWORD: android_key_pass

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release-signed.apk
        path: android/app/build/outputs/apk/release/app-release.apk
